<?php

namespace Proxies\__CG__\Mautic\IntegrationsBundle\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FieldChange extends \Mautic\IntegrationsBundle\Entity\FieldChange implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'id', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'integration', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'objectId', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'objectType', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'modifiedAt', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'columnName', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'columnType', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'columnValue'];
        }

        return ['__isInitialized__', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'id', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'integration', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'objectId', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'objectType', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'modifiedAt', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'columnName', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'columnType', '' . "\0" . 'Mautic\\IntegrationsBundle\\Entity\\FieldChange' . "\0" . 'columnValue'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FieldChange $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntegration(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntegration', []);

        return parent::getIntegration();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntegration($integration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntegration', [$integration]);

        return parent::setIntegration($integration);
    }

    /**
     * {@inheritDoc}
     */
    public function setObjectId(int $id): \Mautic\IntegrationsBundle\Entity\FieldChange
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjectId', [$id]);

        return parent::setObjectId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectId', []);

        return parent::getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjectType(string $type): \Mautic\IntegrationsBundle\Entity\FieldChange
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjectType', [$type]);

        return parent::setObjectType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectType(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectType', []);

        return parent::getObjectType();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt(\DateTime $time): \Mautic\IntegrationsBundle\Entity\FieldChange
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', [$time]);

        return parent::setModifiedAt($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', []);

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnName(string $name): \Mautic\IntegrationsBundle\Entity\FieldChange
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnName', [$name]);

        return parent::setColumnName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnName', []);

        return parent::getColumnName();
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnType(string $type): \Mautic\IntegrationsBundle\Entity\FieldChange
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnType', [$type]);

        return parent::setColumnType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnType(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnType', []);

        return parent::getColumnType();
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnValue(string $value): \Mautic\IntegrationsBundle\Entity\FieldChange
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnValue', [$value]);

        return parent::setColumnValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnValue(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnValue', []);

        return parent::getColumnValue();
    }

}
