<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzXlfCH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzXlfCH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFzXlfCH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFzXlfCH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFzXlfCH\appAppKernelProdContainer([
    'container.build_hash' => 'FzXlfCH',
    'container.build_id' => 'd688bda4',
    'container.build_time' => 1692926962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzXlfCH');
