<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Sbk1mZ9' shared service.

return $this->privates['.service_locator.Sbk1mZ9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'translator' => ['services', 'translator.default', 'getTranslator_DefaultService', false],
], [
    'translator' => '?',
]);
