<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_oauth_server.server' shared service.

return $this->privates['fos_oauth_server.server'] = new \OAuth2\OAuth2(new \FOS\OAuthServerBundle\Storage\OAuthStorage(($this->privates['fos_oauth_server.client_manager.default'] ?? $this->load('getFosOauthServer_ClientManager_DefaultService.php')), ($this->privates['fos_oauth_server.access_token_manager.default'] ?? $this->load('getFosOauthServer_AccessTokenManager_DefaultService.php')), ($this->privates['fos_oauth_server.refresh_token_manager.default'] ?? $this->load('getFosOauthServer_RefreshTokenManager_DefaultService.php')), ($this->privates['fos_oauth_server.auth_code_manager.default'] ?? $this->load('getFosOauthServer_AuthCodeManager_DefaultService.php')), ($this->services['mautic.user.provider'] ?? $this->getMautic_User_ProviderService()), ($this->privates['security.encoder_factory.generic'] ?? $this->getSecurity_EncoderFactory_GenericService())), $this->getParameter('fos_oauth_server.server.options'));
