<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mautic\LeadBundle\Form\Validator\Constraints\FieldAliasKeywordValidator' shared service.

return $this->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'] = new \Mautic\LeadBundle\Form\Validator\Constraints\FieldAliasKeywordValidator(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()), ($this->services['mautic.helper.field.alias'] ?? $this->load('getMautic_Helper_Field_AliasService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.lead.repository.lead_segment_filter_descriptor'] ?? $this->getMautic_Lead_Repository_LeadSegmentFilterDescriptorService()));
