<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'grapesjsbuilder.event.content.subscriber' shared service.

return $this->services['grapesjsbuilder.event.content.subscriber'] = new \MauticPlugin\GrapesJsBuilderBundle\EventSubscriber\InjectCustomContentSubscriber(($this->services['grapesjsbuilder.config'] ?? $this->load('getGrapesjsbuilder_ConfigService.php')), ($this->services['grapesjsbuilder.model'] ?? $this->load('getGrapesjsbuilder_ModelService.php')), ($this->services['grapesjsbuilder.helper.filemanager'] ?? $this->load('getGrapesjsbuilder_Helper_FilemanagerService.php')), ($this->services['mautic.helper.templating'] ?? ($this->services['mautic.helper.templating'] = new \Mautic\CoreBundle\Helper\TemplatingHelper(($this->services['kernel'] ?? $this->get('kernel', 1))))), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['router'] ?? $this->getRouterService()));
