<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.metadata.traceable_cache' shared service.

return $this->privates['jms_serializer.metadata.traceable_cache'] = new \JMS\SerializerBundle\Debug\TraceableDriver(new \Metadata\Cache\FileCache(($this->targetDir.''.'/jms_serializer')));
