<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.helper' shared service.

return $this->privates['knp_menu.helper'] = new \Knp\Menu\Twig\Helper(new \Knp\Menu\Renderer\PsrProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'admin' => ['privates', 'mautic.menu_renderer.admin', 'getMautic_MenuRenderer_AdminService.php', true],
    'extra' => ['privates', 'mautic.menu_renderer.extra', 'getMautic_MenuRenderer_ExtraService.php', true],
    'list' => ['privates', 'knp_menu.renderer.list', 'getKnpMenu_Renderer_ListService.php', true],
    'main' => ['privates', 'mautic.menu_renderer.main', 'getMautic_MenuRenderer_MainService.php', true],
    'mautic' => ['services', 'mautic.menu_renderer', 'getMautic_MenuRendererService.php', true],
    'profile' => ['privates', 'mautic.menu_renderer.profile', 'getMautic_MenuRenderer_ProfileService.php', true],
], [
    'admin' => '?',
    'extra' => '?',
    'list' => '?',
    'main' => '?',
    'mautic' => '?',
    'profile' => '?',
]), 'mautic', [], false), new \Knp\Menu\Provider\ChainProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['knp_menu.menu_provider.lazy'] ?? $this->load('getKnpMenu_MenuProvider_LazyService.php'));
    yield 1 => ($this->privates['knp_menu.menu_provider.builder_alias'] ?? $this->load('getKnpMenu_MenuProvider_BuilderAliasService.php'));
}, 2)), ($this->privates['knp_menu.manipulator'] ?? ($this->privates['knp_menu.manipulator'] = new \Knp\Menu\Util\MenuManipulator())), ($this->services['knp_menu.matcher'] ?? $this->load('getKnpMenu_MatcherService.php')));
