<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lightsaml.credential.credential_store' shared service.

return $this->privates['lightsaml.credential.credential_store'] = (new \LightSaml\Store\Credential\Factory\CredentialFactory())->buildFromOwnCredentialStore(($this->privates['lightsaml.party.idp_entity_descriptor_store'] ?? $this->load('getLightsaml_Party_IdpEntityDescriptorStoreService.php')), ($this->privates['lightsaml.party.sp_entity_descriptor_store'] ?? ($this->privates['lightsaml.party.sp_entity_descriptor_store'] = new \LightSaml\Store\EntityDescriptor\CompositeEntityDescriptorStore())), $this->getEnv('MAUTIC_SAML_ENTITY_ID'), ($this->privates['lightsaml.own.credential_store'] ?? $this->load('getLightsaml_Own_CredentialStoreService.php')), []);
