<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ligthsaml.profile.login_factory' shared service.

return $this->services['ligthsaml.profile.login_factory'] = new \LightSaml\Builder\Profile\WebBrowserSso\Sp\SsoSpSendAuthnRequestProfileBuilderFactory(($this->services['lightsaml.container.build'] ?? $this->load('getLightsaml_Container_BuildService.php')));
