<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.social.helper.twitter_command' shared service.

return $this->services['mautic.social.helper.twitter_command'] = new \MauticPlugin\MauticSocialBundle\Helper\TwitterCommandHelper(($this->services['mautic.lead.model.lead'] ?? $this->getMautic_Lead_Model_LeadService()), ($this->services['mautic.lead.model.field'] ?? $this->getMautic_Lead_Model_FieldService()), ($this->services['mautic.social.model.monitoring'] ?? $this->load('getMautic_Social_Model_MonitoringService.php')), ($this->services['mautic.social.model.postcount'] ?? $this->load('getMautic_Social_Model_PostcountService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
