<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.type.action.sendwebhook' shared service.

return $this->services['mautic.campaign.type.action.sendwebhook'] = new \Mautic\WebhookBundle\Form\Type\CampaignEventSendWebhookType(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
