<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.plugin.clearbit.lookup_helper' shared service.

return $this->services['mautic.plugin.clearbit.lookup_helper'] = new \MauticPlugin\MauticClearbitBundle\Helper\LookupHelper(($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()), ($this->services['mautic.helper.user'] ?? $this->getMautic_Helper_UserService()), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()), ($this->services['mautic.lead.model.lead'] ?? $this->getMautic_Lead_Model_LeadService()), ($this->services['mautic.lead.model.company'] ?? $this->getMautic_Lead_Model_CompanyService()));
