<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.asset.reportbundle.subscriber' shared service.

return $this->services['mautic.asset.reportbundle.subscriber'] = new \Mautic\AssetBundle\EventListener\ReportSubscriber(($this->services['mautic.lead.model.company_report_data'] ?? $this->load('getMautic_Lead_Model_CompanyReportDataService.php')), ($this->services['mautic.asset.repository.download'] ?? $this->load('getMautic_Asset_Repository_DownloadService.php')));
