<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.segment.config' shared service.

return $this->services['mautic.segment.config'] = new \Mautic\LeadBundle\Form\Type\SegmentConfigType();
