<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.leadbundle.subscriber' shared service.

return $this->services['mautic.form.leadbundle.subscriber'] = new \Mautic\FormBundle\EventListener\LeadSubscriber(($this->services['mautic.form.model.form'] ?? $this->getMautic_Form_Model_FormService()), ($this->services['mautic.page.model.page'] ?? $this->getMautic_Page_Model_PageService()), ($this->services['mautic.form.repository.submission'] ?? $this->load('getMautic_Form_Repository_SubmissionService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['router'] ?? $this->getRouterService()));
