<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.pagelist' shared service.

return $this->services['mautic.form.type.pagelist'] = new \Mautic\PageBundle\Form\Type\PageListType(($this->services['mautic.page.model.page'] ?? $this->getMautic_Page_Model_PageService()), ($this->services['mautic.security'] ?? $this->getMautic_SecurityService()));
