<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.social.form.type.network.twitter.custom' shared service.

return $this->services['mautic.social.form.type.network.twitter.custom'] = new \MauticPlugin\MauticSocialBundle\Form\Type\TwitterCustomType();
