<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.helper.mailbox' shared service.

return $this->services['mautic.helper.mailbox'] = new \Mautic\EmailBundle\MonitoredEmail\Mailbox(($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))), ($this->services['mautic.helper.paths'] ?? $this->getMautic_Helper_PathsService()));
