<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.plugin.facade.reload' shared service.

return $this->services['mautic.plugin.facade.reload'] = new \Mautic\PluginBundle\Facade\ReloadFacade(($this->services['mautic.plugin.model.plugin'] ?? $this->getMautic_Plugin_Model_PluginService()), ($this->services['mautic.plugin.helper.reload'] ?? $this->load('getMautic_Plugin_Helper_ReloadService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
