<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.generated_columns.subscriber' shared service.

return $this->services['mautic.lead.generated_columns.subscriber'] = new \Mautic\LeadBundle\EventListener\GeneratedColumnSubscriber(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
