<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.dynamic_content_filter' shared service.

return $this->services['mautic.form.type.dynamic_content_filter'] = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterType(($this->services['mautic.integrations.helper.builder_integrations'] ?? $this->getMautic_Integrations_Helper_BuilderIntegrationsService()));
