<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.stats.helper_sent' shared service.

return $this->services['mautic.email.stats.helper_sent'] = new \Mautic\EmailBundle\Stats\Helper\SentHelper(($this->services['mautic.stats.aggregate.collector'] ?? $this->load('getMautic_Stats_Aggregate_CollectorService.php')), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['mautic.generated.columns.provider'] ?? $this->load('getMautic_Generated_Columns_ProviderService.php')), ($this->services['mautic.helper.user'] ?? $this->getMautic_Helper_UserService()));
