<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.lead_dashboard_leads_lifetime_widget' shared service.

return $this->services['mautic.form.type.lead_dashboard_leads_lifetime_widget'] = new \Mautic\LeadBundle\Form\Type\DashboardLeadsLifetimeWidgetType(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
