<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.helper.hash' shared service.

return $this->services['mautic.helper.hash'] = new \Mautic\CoreBundle\Helper\HashHelper\HashHelper();
