<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.social.linkedin' shared service.

return $this->services['mautic.form.type.social.linkedin'] = new \MauticPlugin\MauticSocialBundle\Form\Type\LinkedInType();
