<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.config.form.escape_transformer' shared service.

return $this->services['mautic.config.form.escape_transformer'] = new \Mautic\ConfigBundle\Form\Type\EscapeTransformer($this->getEnv('json:resolve:MAUTIC_CONFIG_ALLOWED_PARAMETERS'));
