<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.coreconfig.iplookup_download_data_store_button' shared service.

return $this->services['mautic.form.type.coreconfig.iplookup_download_data_store_button'] = new \Mautic\CoreBundle\Form\Type\IpLookupDownloadDataStoreButtonType(($this->services['mautic.helper.template.date'] ?? $this->load('getMautic_Helper_Template_DateService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
