<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.sync.notification.helper_user_notification' shared service.

return $this->services['mautic.integrations.sync.notification.helper_user_notification'] = new \Mautic\IntegrationsBundle\Sync\Notification\Helper\UserNotificationHelper(($this->services['mautic.integrations.sync.notification.writer'] ?? $this->load('getMautic_Integrations_Sync_Notification_WriterService.php')), ($this->services['mautic.integrations.sync.notification.helper_user'] ?? $this->load('getMautic_Integrations_Sync_Notification_HelperUserService.php')), ($this->services['mautic.integrations.sync.notification.helper.owner_provider'] ?? $this->load('getMautic_Integrations_Sync_Notification_Helper_OwnerProviderService.php')), ($this->services['mautic.integrations.sync.notification.helper_route'] ?? $this->load('getMautic_Integrations_Sync_Notification_HelperRouteService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
