<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.helper.properties.accessor' shared service.

return $this->services['mautic.form.helper.properties.accessor'] = new \Mautic\FormBundle\Helper\PropertiesAccessor(($this->services['mautic.form.model.form'] ?? $this->getMautic_Form_Model_FormService()));
