<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.report.command.export_scheduler' shared service.

return $this->services['mautic.report.command.export_scheduler'] = new \Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand(($this->services['mautic.report.model.report_exporter'] ?? $this->load('getMautic_Report_Model_ReportExporterService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
