<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.leaddevice' shared service.

return $this->services['mautic.form.type.leaddevice'] = new \Mautic\LeadBundle\Form\Type\DeviceType();
