<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.clearbit_lookup' shared service.

return $this->services['mautic.form.type.clearbit_lookup'] = new \MauticPlugin\MauticClearbitBundle\Form\Type\LookupType();
