<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.asset.campaignbundle.subscriber' shared service.

return $this->services['mautic.asset.campaignbundle.subscriber'] = new \Mautic\AssetBundle\EventListener\CampaignSubscriber(($this->services['mautic.campaign.executioner.realtime'] ?? $this->load('getMautic_Campaign_Executioner_RealtimeService.php')));
