<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.command.sync' shared service.

return $this->services['mautic.integrations.command.sync'] = new \Mautic\IntegrationsBundle\Command\SyncCommand(($this->services['mautic.integrations.sync.service'] ?? $this->load('getMautic_Integrations_Sync_ServiceService.php')), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
