<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.campaignbundle.subscriber' shared service.

return $this->services['mautic.lead.campaignbundle.subscriber'] = new \Mautic\LeadBundle\EventListener\CampaignSubscriber(($this->services['mautic.helper.ip_lookup'] ?? $this->getMautic_Helper_IpLookupService()), ($this->services['mautic.lead.model.lead'] ?? $this->getMautic_Lead_Model_LeadService()), ($this->services['mautic.lead.model.field'] ?? $this->getMautic_Lead_Model_FieldService()), ($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()), ($this->services['mautic.lead.model.company'] ?? $this->getMautic_Lead_Model_CompanyService()), ($this->services['mautic.campaign.model.campaign'] ?? $this->load('getMautic_Campaign_Model_CampaignService.php')), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
