<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.update.step.update_translations' shared service.

return $this->services['mautic.update.step.update_translations'] = new \Mautic\CoreBundle\Update\Step\UpdateTranslationsStep(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.helper.language'] ?? $this->load('getMautic_Helper_LanguageService.php')), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));
