<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.plugin.leadbundle.subscriber' shared service.

return $this->services['mautic.plugin.leadbundle.subscriber'] = new \Mautic\PluginBundle\EventListener\LeadSubscriber(($this->services['mautic.plugin.model.plugin'] ?? $this->getMautic_Plugin_Model_PluginService()));
