<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.core.validator.file_upload' shared service.

return $this->services['mautic.core.validator.file_upload'] = new \Mautic\CoreBundle\Validator\FileUploadValidator(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
