<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'marketplace.command.remove' shared service.

return $this->services['marketplace.command.remove'] = new \Mautic\MarketplaceBundle\Command\RemoveCommand(($this->services['mautic.helper.composer'] ?? $this->load('getMautic_Helper_ComposerService.php')), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));
