<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.report.model.report_file_writer' shared service.

return $this->services['mautic.report.model.report_file_writer'] = new \Mautic\ReportBundle\Model\ReportFileWriter(($this->services['mautic.report.model.csv_exporter'] ?? $this->load('getMautic_Report_Model_CsvExporterService.php')), ($this->services['mautic.report.model.export_handler'] ?? $this->load('getMautic_Report_Model_ExportHandlerService.php')));
