<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.executioner.inactive' shared service.

return $this->services['mautic.campaign.executioner.inactive'] = new \Mautic\CampaignBundle\Executioner\InactiveExecutioner(($this->services['mautic.campaign.contact_finder.inactive'] ?? $this->load('getMautic_Campaign_ContactFinder_InactiveService.php')), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.campaign.scheduler'] ?? $this->load('getMautic_Campaign_SchedulerService.php')), ($this->services['mautic.campaign.helper.inactivity'] ?? $this->load('getMautic_Campaign_Helper_InactivityService.php')), ($this->services['mautic.campaign.event_executioner'] ?? $this->load('getMautic_Campaign_EventExecutionerService.php')));
