<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.menu.builder' shared service.

return $this->services['mautic.menu.builder'] = new \Mautic\CoreBundle\Menu\MenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['knp_menu.matcher'] ?? $this->load('getKnpMenu_MatcherService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['mautic.helper.menu'] ?? $this->getMautic_Helper_MenuService()));
