<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.notification.campaignbundle.subscriber' shared service.

return $this->services['mautic.notification.campaignbundle.subscriber'] = new \Mautic\NotificationBundle\EventListener\CampaignSubscriber(($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()), ($this->services['mautic.notification.model.notification'] ?? $this->load('getMautic_Notification_Model_NotificationService.php')), ($this->services['mautic.notification.api'] ?? $this->load('getMautic_Notification_ApiService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['mautic.lead.model.dnc'] ?? $this->load('getMautic_Lead_Model_DncService.php')));
