<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.security.saml.entity_descriptor_store' shared service.

return $this->services['mautic.security.saml.entity_descriptor_store'] = new \Mautic\UserBundle\Security\SAML\Store\EntityDescriptorStore(($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
