<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.email_to_user' shared service.

return $this->services['mautic.form.type.email_to_user'] = new \Mautic\EmailBundle\Form\Type\EmailToUserType();
