<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.point.leadbundle.subscriber' shared service.

return $this->services['mautic.point.leadbundle.subscriber'] = new \Mautic\PointBundle\EventListener\LeadSubscriber(($this->services['mautic.point.model.trigger'] ?? $this->load('getMautic_Point_Model_TriggerService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.lead.repository.points_change_log'] ?? $this->load('getMautic_Lead_Repository_PointsChangeLogService.php')), ($this->services['mautic.point.repository.lead_point_log'] ?? $this->load('getMautic_Point_Repository_LeadPointLogService.php')), ($this->services['mautic.point.repository.lead_trigger_log'] ?? $this->load('getMautic_Point_Repository_LeadTriggerLogService.php')));
