<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.entity_lookup' shared service.

return $this->services['mautic.form.type.entity_lookup'] = new \Mautic\CoreBundle\Form\Type\EntityLookupType(($this->services['mautic.model.factory'] ?? ($this->services['mautic.model.factory'] = new \Mautic\CoreBundle\Factory\ModelFactory($this))), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['router'] ?? $this->getRouterService()));
