<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.pagebuilder.subscriber' shared service.

return $this->services['mautic.pagebuilder.subscriber'] = new \Mautic\PageBundle\EventListener\BuilderSubscriber(($this->services['mautic.security'] ?? $this->getMautic_SecurityService()), ($this->services['mautic.page.helper.token'] ?? $this->getMautic_Page_Helper_TokenService()), ($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()), ($this->services['mautic.page.model.page'] ?? $this->getMautic_Page_Model_PageService()), ($this->services['mautic.helper.token_builder.factory'] ?? $this->load('getMautic_Helper_TokenBuilder_FactoryService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['mautic.helper.templating'] ?? ($this->services['mautic.helper.templating'] = new \Mautic\CoreBundle\Helper\TemplatingHelper(($this->services['kernel'] ?? $this->get('kernel', 1))))));
