<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.sync.data_exchange.mautic.field_helper' shared service.

return $this->services['mautic.integrations.sync.data_exchange.mautic.field_helper'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Helper\FieldHelper(($this->services['mautic.lead.model.field'] ?? $this->getMautic_Lead_Model_FieldService()), ($this->services['mautic.integrations.helper.variable_expresser'] ?? ($this->services['mautic.integrations.helper.variable_expresser'] = new \Mautic\IntegrationsBundle\Sync\VariableExpresser\VariableExpresserHelper())), ($this->services['mautic.channel.helper.channel_list'] ?? $this->getMautic_Channel_Helper_ChannelListService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['mautic.integrations.internal.object_provider'] ?? $this->load('getMautic_Integrations_Internal_ObjectProviderService.php')));
