<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.transport_type' shared service.

$this->services['mautic.email.transport_type'] = $instance = new \Mautic\EmailBundle\Model\TransportType();

$instance->addTransport('mautic.transport.momentum', 'mautic.email.config.mailer_transport.momentum', true, true, false, false, true);

return $instance;
