<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.page.fixture.page_hit' shared service.

return $this->services['mautic.page.fixture.page_hit'] = new \Mautic\PageBundle\DataFixtures\ORM\LoadPageHitData(($this->services['mautic.page.model.page'] ?? $this->getMautic_Page_Model_PageService()));
