<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.form_submitaction_sendemail' shared service.

$this->services['mautic.form.type.form_submitaction_sendemail'] = $instance = new \Mautic\FormBundle\Form\Type\SubmitActionEmailType(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));

$instance->setFieldModel(($this->services['mautic.form.model.field'] ?? $this->getMautic_Form_Model_FieldService()));
$instance->setFormModel(($this->services['mautic.form.model.form'] ?? $this->getMautic_Form_Model_FormService()));

return $instance;
