<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.user' shared service.

return $this->services['mautic.form.type.user'] = new \Mautic\UserBundle\Form\Type\UserType(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.user.model.user'] ?? $this->getMautic_User_Model_UserService()), ($this->services['mautic.helper.language'] ?? $this->load('getMautic_Helper_LanguageService.php')));
