<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.install.configurator.step.doctrine' shared service.

$a = ($this->services['mautic.configurator'] ?? $this->load('getMautic_ConfiguratorService.php'));

if (isset($this->services['mautic.install.configurator.step.doctrine'])) {
    return $this->services['mautic.install.configurator.step.doctrine'];
}

return $this->services['mautic.install.configurator.step.doctrine'] = new \Mautic\InstallBundle\Configurator\Step\DoctrineStep($a);
