<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.message.processor.feedbackloop' shared service.

return $this->services['mautic.message.processor.feedbackloop'] = new \Mautic\EmailBundle\MonitoredEmail\Processor\FeedbackLoop(($this->services['mautic.message.search.contact'] ?? $this->load('getMautic_Message_Search_ContactService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()), ($this->services['mautic.lead.model.dnc'] ?? $this->load('getMautic_Lead_Model_DncService.php')));
