<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.field.notification.custom_field' shared service.

return $this->services['mautic.lead.field.notification.custom_field'] = new \Mautic\LeadBundle\Field\Notification\CustomFieldNotification(($this->services['mautic.core.model.notification'] ?? $this->getMautic_Core_Model_NotificationService()), ($this->services['mautic.user.model.user'] ?? $this->getMautic_User_Model_UserService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
