<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.sms.transport_chain' shared service.

$this->services['mautic.sms.transport_chain'] = $instance = new \Mautic\SmsBundle\Sms\TransportChain($this->getEnv('nullable:resolve:MAUTIC_SMS_TRANSPORT'), ($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));

$instance->addTransport('mautic.sms.twilio.transport', ($this->services['mautic.sms.twilio.transport'] ?? $this->load('getMautic_Sms_Twilio_TransportService.php')), 'mautic.sms.twilio.transport', 'Twilio');

return $instance;
