<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.api.rate_limit_generate_key.subscriber' shared service.

return $this->services['mautic.api.rate_limit_generate_key.subscriber'] = new \Mautic\ApiBundle\EventListener\RateLimitGenerateKeySubscriber(($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
