<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.citrix.campaignbundle.subscriber' shared service.

$this->services['mautic.citrix.campaignbundle.subscriber'] = $instance = new \MauticPlugin\MauticCitrixBundle\EventListener\CampaignSubscriber(($this->services['mautic.citrix.model.citrix'] ?? $this->load('getMautic_Citrix_Model_CitrixService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.helper.templating'] ?? ($this->services['mautic.helper.templating'] = new \Mautic\CoreBundle\Helper\TemplatingHelper(($this->services['kernel'] ?? $this->get('kernel', 1))))));

$instance->setEmailModel(($this->services['mautic.email.model.email'] ?? $this->load('getMautic_Email_Model_EmailService.php')));

return $instance;
