<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.helper.field_validator' shared service.

return $this->services['mautic.integrations.helper.field_validator'] = new \Mautic\IntegrationsBundle\Helper\FieldValidationHelper(($this->services['mautic.integrations.sync.data_exchange.mautic.field_helper'] ?? $this->load('getMautic_Integrations_Sync_DataExchange_Mautic_FieldHelperService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
