<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.query.builder.special.leadlist' shared service.

return $this->services['mautic.lead.query.builder.special.leadlist'] = new \Mautic\LeadBundle\Segment\Query\Filter\SegmentReferenceFilterQueryBuilder(($this->services['mautic.lead.model.random_parameter_name'] ?? ($this->services['mautic.lead.model.random_parameter_name'] = new \Mautic\LeadBundle\Segment\RandomParameterName())), ($this->services['mautic.lead.repository.lead_segment_query_builder'] ?? $this->getMautic_Lead_Repository_LeadSegmentQueryBuilderService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic.lead.model.lead_segment_filter_factory'] ?? $this->getMautic_Lead_Model_LeadSegmentFilterFactoryService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
