<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.point.type.action' shared service.

return $this->services['mautic.point.type.action'] = new \Mautic\PointBundle\Form\Type\PointActionType();
