<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.report.model.send_schedule' shared service.

return $this->services['mautic.report.model.send_schedule'] = new \Mautic\ReportBundle\Scheduler\Model\SendSchedule(($this->services['mautic.helper.mailer'] ?? $this->getMautic_Helper_MailerService()), ($this->services['mautic.report.model.message_schedule'] ?? $this->load('getMautic_Report_Model_MessageScheduleService.php')), ($this->services['mautic.report.model.file_handler'] ?? $this->load('getMautic_Report_Model_FileHandlerService.php')));
