<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.asset' shared service.

return $this->services['mautic.form.type.asset'] = new \Mautic\AssetBundle\Form\Type\AssetType(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.asset.model.asset'] ?? $this->getMautic_Asset_Model_AssetService()));
