<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead_list.constraint.in_use' shared service.

return $this->services['mautic.lead_list.constraint.in_use'] = new \Mautic\LeadBundle\Form\Validator\Constraints\SegmentInUseValidator(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()));
