<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.maxmind.doNotSellList' shared service.

return $this->services['mautic.maxmind.doNotSellList'] = new \Mautic\CoreBundle\IpLookup\DoNotSellList\MaxMindDoNotSellList(($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
