<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.validator.constraint.file_extension_constraint_validator' shared service.

return $this->services['mautic.form.validator.constraint.file_extension_constraint_validator'] = new \Mautic\FormBundle\Validator\Constraint\FileExtensionConstraintValidator(($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
