<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.subscriber.donotcontact' shared service.

return $this->services['mautic.lead.subscriber.donotcontact'] = new \Mautic\LeadBundle\EventListener\DoNotContactSubscriber(($this->services['mautic.lead.model.dnc'] ?? $this->load('getMautic_Lead_Model_DncService.php')));
