<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'marketplace.controller.cache' shared service.

$this->services['marketplace.controller.cache'] = $instance = new \Mautic\MarketplaceBundle\Controller\CacheController(($this->services['mautic.security'] ?? $this->getMautic_SecurityService()), ($this->services['marketplace.service.config'] ?? $this->getMarketplace_Service_ConfigService()), ($this->services['marketplace.service.allowlist'] ?? $this->load('getMarketplace_Service_AllowlistService.php')));

$instance->setContainer($this);

return $instance;
