<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.command.queue' shared service.

return $this->services['mautic.email.command.queue'] = new \Mautic\EmailBundle\Command\ProcessEmailQueueCommand(($this->services['swiftmailer.mailer.default.transport.real'] ?? $this->getSwiftmailer_Mailer_Default_Transport_RealService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
