<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.emailvariant' shared service.

return $this->services['mautic.form.type.emailvariant'] = new \Mautic\EmailBundle\Form\Type\VariantType(($this->services['mautic.email.model.email'] ?? $this->load('getMautic_Email_Model_EmailService.php')));
