<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.message.search.contact' shared service.

return $this->services['mautic.message.search.contact'] = new \Mautic\EmailBundle\MonitoredEmail\Search\ContactFinder(($this->services['mautic.email.repository.stat'] ?? $this->load('getMautic_Email_Repository_StatService.php')), ($this->services['mautic.lead.repository.lead'] ?? $this->getMautic_Lead_Repository_LeadService()), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));
