<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.helper.sync_mapping' shared service.

return $this->services['mautic.integrations.helper.sync_mapping'] = new \Mautic\IntegrationsBundle\Sync\Helper\MappingHelper(($this->services['mautic.lead.model.field'] ?? $this->getMautic_Lead_Model_FieldService()), ($this->services['mautic.integrations.repository.object_mapping'] ?? $this->load('getMautic_Integrations_Repository_ObjectMappingService.php')), ($this->services['mautic.integrations.internal.object_provider'] ?? $this->load('getMautic_Integrations_Internal_ObjectProviderService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
