<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.install.configurator.step.email' shared service.

return $this->services['mautic.install.configurator.step.email'] = new \Mautic\InstallBundle\Configurator\Step\EmailStep(($this->services['session'] ?? $this->getSessionService()));
