<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.transport.momentum.callback' shared service.

return $this->services['mautic.transport.momentum.callback'] = new \Mautic\EmailBundle\Swiftmailer\Momentum\Callback\MomentumCallback(($this->services['mautic.email.model.transport_callback'] ?? $this->load('getMautic_Email_Model_TransportCallbackService.php')));
