<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.user.fixture.user' shared service.

return $this->services['mautic.user.fixture.user'] = new \Mautic\UserBundle\DataFixtures\ORM\LoadUserData(($this->services['security.password_encoder'] ?? $this->getSecurity_PasswordEncoderService()));
