<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.security.saml.id_store' shared service.

return $this->services['mautic.security.saml.id_store'] = new \Mautic\UserBundle\Security\SAML\Store\IdStore(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['lightsaml.system.time_provider'] ?? ($this->privates['lightsaml.system.time_provider'] = new \LightSaml\Provider\TimeProvider\SystemTimeProvider())));
