<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.stats.helper_container' shared service.

$this->services['mautic.email.stats.helper_container'] = $instance = new \Mautic\EmailBundle\Stats\StatHelperContainer();

$instance->addHelper(($this->services['mautic.email.stats.helper_bounced'] ?? $this->load('getMautic_Email_Stats_HelperBouncedService.php')));
$instance->addHelper(($this->services['mautic.email.stats.helper_clicked'] ?? $this->load('getMautic_Email_Stats_HelperClickedService.php')));
$instance->addHelper(($this->services['mautic.email.stats.helper_failed'] ?? $this->load('getMautic_Email_Stats_HelperFailedService.php')));
$instance->addHelper(($this->services['mautic.email.stats.helper_opened'] ?? $this->load('getMautic_Email_Stats_HelperOpenedService.php')));
$instance->addHelper(($this->services['mautic.email.stats.helper_sent'] ?? $this->load('getMautic_Email_Stats_HelperSentService.php')));
$instance->addHelper(($this->services['mautic.email.stats.helper_unsubscribed'] ?? $this->load('getMautic_Email_Stats_HelperUnsubscribedService.php')));

return $instance;
