<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.contact_finder.inactive' shared service.

return $this->services['mautic.campaign.contact_finder.inactive'] = new \Mautic\CampaignBundle\Executioner\ContactFinder\InactiveContactFinder(($this->services['mautic.lead.repository.lead'] ?? $this->getMautic_Lead_Repository_LeadService()), ($this->services['mautic.campaign.repository.lead'] ?? $this->load('getMautic_Campaign_Repository_LeadService.php')), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));
