<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.executioner.kickoff' shared service.

return $this->services['mautic.campaign.executioner.kickoff'] = new \Mautic\CampaignBundle\Executioner\KickoffExecutioner(($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()), ($this->services['mautic.campaign.contact_finder.kickoff'] ?? $this->load('getMautic_Campaign_ContactFinder_KickoffService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.campaign.event_executioner'] ?? $this->load('getMautic_Campaign_EventExecutionerService.php')), ($this->services['mautic.campaign.scheduler'] ?? $this->load('getMautic_Campaign_SchedulerService.php')));
