<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.pagebundle.subscriber' shared service.

return $this->services['mautic.email.pagebundle.subscriber'] = new \Mautic\EmailBundle\EventListener\PageSubscriber(($this->services['mautic.email.model.email'] ?? $this->load('getMautic_Email_Model_EmailService.php')), ($this->services['mautic.campaign.executioner.realtime'] ?? $this->load('getMautic_Campaign_Executioner_RealtimeService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
