<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.validator.leadlistaccess' shared service.

return $this->services['mautic.validator.leadlistaccess'] = new \Mautic\LeadBundle\Form\Validator\Constraints\LeadListAccessValidator(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()));
