<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.event.dispatcher' shared service.

return $this->services['mautic.lead.event.dispatcher'] = new \Mautic\LeadBundle\Helper\LeadChangeEventDispatcher(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
