<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'MauticPlugin\MauticSocialBundle\Command\MauticSocialMonitoringCommand' shared autowired service.

return $this->services['MauticPlugin\\MauticSocialBundle\\Command\\MauticSocialMonitoringCommand'] = new \MauticPlugin\MauticSocialBundle\Command\MauticSocialMonitoringCommand();
