<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.coreconfig' shared service.

return $this->services['mautic.form.type.coreconfig'] = new \Mautic\CoreBundle\Form\Type\ConfigType(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.helper.language'] ?? $this->load('getMautic_Helper_LanguageService.php')), ($this->services['mautic.ip_lookup.factory'] ?? $this->getMautic_IpLookup_FactoryService()), $this->parameters['mautic.ip_lookup_services'], ($this->services['mautic.ip_lookup'] ?? $this->getMautic_IpLookupService()));
