<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.social.form.type.monitoring' shared service.

return $this->services['mautic.social.form.type.monitoring'] = new \MauticPlugin\MauticSocialBundle\Form\Type\MonitoringType(($this->services['mautic.social.model.monitoring'] ?? $this->load('getMautic_Social_Model_MonitoringService.php')));
