<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.command.summarize' shared service.

return $this->services['mautic.campaign.command.summarize'] = new \Mautic\CampaignBundle\Command\SummarizeCommand(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['mautic.campaign.model.summary'] ?? $this->load('getMautic_Campaign_Model_SummaryService.php')));
