<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.leadbundle.subscriber' shared service.

return $this->services['mautic.campaign.leadbundle.subscriber'] = new \Mautic\CampaignBundle\EventListener\LeadSubscriber(($this->services['mautic.campaign.membership.manager'] ?? $this->load('getMautic_Campaign_Membership_ManagerService.php')), ($this->services['mautic.campaign.event_collector'] ?? $this->load('getMautic_Campaign_EventCollectorService.php')), ($this->services['mautic.campaign.model.campaign'] ?? $this->load('getMautic_Campaign_Model_CampaignService.php')), ($this->services['mautic.lead.model.lead'] ?? $this->getMautic_Lead_Model_LeadService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['router'] ?? $this->getRouterService()));
