<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.generated_columns.subscriber' shared service.

return $this->services['mautic.email.generated_columns.subscriber'] = new \Mautic\EmailBundle\EventListener\GeneratedColumnSubscriber();
