<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.helper.command' shared service.

return $this->services['mautic.helper.command'] = new \Mautic\CoreBundle\Helper\CommandHelper(($this->services['kernel'] ?? $this->get('kernel', 1)));
