<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.pointbundle.subscriber' shared service.

return $this->services['mautic.lead.pointbundle.subscriber'] = new \Mautic\LeadBundle\EventListener\PointSubscriber(($this->services['mautic.lead.model.lead'] ?? $this->getMautic_Lead_Model_LeadService()));
