<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.webhook.notificator.webhookkillnotificator' shared service.

return $this->services['mautic.webhook.notificator.webhookkillnotificator'] = new \Mautic\WebhookBundle\Notificator\WebhookKillNotificator(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['mautic.core.model.notification'] ?? $this->getMautic_Core_Model_NotificationService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic.helper.mailer'] ?? $this->getMautic_Helper_MailerService()), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
