<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.api.oauth.event_listener' shared service.

return $this->services['mautic.api.oauth.event_listener'] = new \Mautic\ApiBundle\EventListener\OAuthEventListener(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic.security'] ?? $this->getMautic_SecurityService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
