<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'marketplace.service.allowlist' shared service.

return $this->services['marketplace.service.allowlist'] = new \Mautic\MarketplaceBundle\Service\Allowlist(($this->services['marketplace.service.config'] ?? $this->getMarketplace_Service_ConfigService()), ($this->services['mautic.cache.provider'] ?? $this->getMautic_Cache_ProviderService()), ($this->services['mautic.http.client'] ?? ($this->services['mautic.http.client'] = new \GuzzleHttp\Client())));
