<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.campaign.subscriber' shared service.

return $this->services['mautic.campaign.subscriber'] = new \Mautic\CampaignBundle\EventListener\CampaignSubscriber(($this->services['mautic.helper.ip_lookup'] ?? $this->getMautic_Helper_IpLookupService()), ($this->services['mautic.core.model.auditlog'] ?? $this->getMautic_Core_Model_AuditlogService()), ($this->services['mautic.campaign.service.campaign'] ?? $this->load('getMautic_Campaign_Service_CampaignService.php')), ($this->services['mautic.core.service.flashbag'] ?? $this->getMautic_Core_Service_FlashbagService()));
