<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.campaignbundle.subscriber' shared service.

return $this->services['mautic.email.campaignbundle.subscriber'] = new \Mautic\EmailBundle\EventListener\CampaignSubscriber(($this->services['mautic.email.model.email'] ?? $this->load('getMautic_Email_Model_EmailService.php')), ($this->services['mautic.campaign.executioner.realtime'] ?? $this->load('getMautic_Campaign_Executioner_RealtimeService.php')), ($this->services['mautic.email.model.send_email_to_user'] ?? $this->load('getMautic_Email_Model_SendEmailToUserService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
