<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.timeline_events.segment.subscriber' shared service.

return $this->services['mautic.lead.timeline_events.segment.subscriber'] = new \Mautic\LeadBundle\EventListener\TimelineEventLogSegmentSubscriber(($this->services['mautic.lead.repository.lead_event_log'] ?? $this->load('getMautic_Lead_Repository_LeadEventLogService.php')), ($this->services['mautic.helper.user'] ?? $this->getMautic_Helper_UserService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
