<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic_integration.pipedrive.import.company' shared service.

return $this->services['mautic_integration.pipedrive.import.company'] = new \MauticPlugin\MauticCrmBundle\Integration\Pipedrive\Import\CompanyImport(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic.lead.model.company'] ?? $this->getMautic_Lead_Model_CompanyService()));
