<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.assetconfig' shared service.

return $this->services['mautic.form.type.assetconfig'] = new \Mautic\AssetBundle\Form\Type\ConfigType();
