<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.transport.sendgrid_api' shared service.

return $this->services['mautic.transport.sendgrid_api'] = new \Mautic\EmailBundle\Swiftmailer\Transport\SendgridApiTransport(($this->services['mautic.transport.sendgrid_api.facade'] ?? $this->load('getMautic_Transport_SendgridApi_FacadeService.php')), ($this->services['mautic.transport.sendgrid_api.calback'] ?? $this->load('getMautic_Transport_SendgridApi_CalbackService.php')));
