<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.install.configurator.step.check' shared service.

$a = ($this->services['mautic.configurator'] ?? $this->load('getMautic_ConfiguratorService.php'));

if (isset($this->services['mautic.install.configurator.step.check'])) {
    return $this->services['mautic.install.configurator.step.check'];
}

return $this->services['mautic.install.configurator.step.check'] = new \Mautic\InstallBundle\Configurator\Step\CheckStep($a, (\dirname(__DIR__, 4).'/app'), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['mautic.cipher.openssl'] ?? ($this->services['mautic.cipher.openssl'] = new \Mautic\CoreBundle\Security\Cryptography\Cipher\Symmetric\OpenSSLCipher('prod'))));
