<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.citrix.formbundle.subscriber' shared service.

$this->services['mautic.citrix.formbundle.subscriber'] = $instance = new \MauticPlugin\MauticCitrixBundle\EventListener\FormSubscriber(($this->services['mautic.citrix.model.citrix'] ?? $this->load('getMautic_Citrix_Model_CitrixService.php')), ($this->services['mautic.form.model.form'] ?? $this->getMautic_Form_Model_FormService()), ($this->services['mautic.form.model.submission'] ?? $this->load('getMautic_Form_Model_SubmissionService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic.helper.templating'] ?? ($this->services['mautic.helper.templating'] = new \Mautic\CoreBundle\Helper\TemplatingHelper(($this->services['kernel'] ?? $this->get('kernel', 1))))));

$instance->setEmailModel(($this->services['mautic.email.model.email'] ?? $this->load('getMautic_Email_Model_EmailService.php')));

return $instance;
