<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.focus.form.type.focus' shared service.

return $this->services['mautic.focus.form.type.focus'] = new \MauticPlugin\MauticFocusBundle\Form\Type\FocusType(($this->services['mautic.security'] ?? $this->getMautic_SecurityService()));
