<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.dashboard.model.dashboard' shared service.

$a = ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this)));

$this->services['mautic.dashboard.model.dashboard'] = $instance = new \Mautic\DashboardBundle\Model\DashboardModel($a, ($this->services['mautic.helper.paths'] ?? $this->getMautic_Helper_PathsService()), ($this->services['symfony.filesystem'] ?? ($this->services['symfony.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));

$instance->setEntityManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
$instance->setSecurity(($this->services['mautic.security'] ?? $this->getMautic_SecurityService()));
$instance->setDispatcher(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
$instance->setTranslator(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
$instance->setUserHelper(($this->services['mautic.helper.user'] ?? $this->getMautic_Helper_UserService()));
$instance->setCoreParametersHelper($a);
$instance->setRouter(($this->services['router'] ?? $this->getRouterService()));
$instance->setLogger(($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));
$instance->setSession(($this->services['session'] ?? $this->getSessionService()));

return $instance;
