<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.passwordreset' shared service.

return $this->services['mautic.form.type.passwordreset'] = new \Mautic\UserBundle\Form\Type\PasswordResetType();
