<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.asset.leadbundle.subscriber' shared service.

return $this->services['mautic.asset.leadbundle.subscriber'] = new \Mautic\AssetBundle\EventListener\LeadSubscriber(($this->services['mautic.asset.model.asset'] ?? $this->getMautic_Asset_Model_AssetService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['mautic.asset.repository.download'] ?? $this->load('getMautic_Asset_Repository_DownloadService.php')));
