<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.report.model.excel_exporter' shared service.

return $this->services['mautic.report.model.excel_exporter'] = new \Mautic\ReportBundle\Model\ExcelExporter(($this->services['mautic.helper.template.formatter'] ?? $this->load('getMautic_Helper_Template_FormatterService.php')));
