<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.security.authentication_handler' shared service.

return $this->services['mautic.security.authentication_handler'] = new \Mautic\UserBundle\Security\Authentication\AuthenticationHandler(($this->services['router'] ?? $this->getRouterService()));
