<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.sms.controller.reply' shared service.

$this->services['mautic.sms.controller.reply'] = $instance = new \Mautic\SmsBundle\Controller\ReplyController(($this->services['mautic.sms.callback_handler_container'] ?? $this->load('getMautic_Sms_CallbackHandlerContainerService.php')), ($this->services['mautic.sms.helper.reply'] ?? $this->load('getMautic_Sms_Helper_ReplyService.php')));

$instance->setContainer($this);

return $instance;
