<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.dynamic_content_filter_entry' shared service.

return $this->services['mautic.form.type.dynamic_content_filter_entry'] = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()), ($this->services['mautic.stage.model.stage'] ?? $this->load('getMautic_Stage_Model_StageService.php')), ($this->services['mautic.integrations.helper.builder_integrations'] ?? $this->getMautic_Integrations_Helper_BuilderIntegrationsService()));
