<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.page.helper.tracking' shared service.

return $this->services['mautic.page.helper.tracking'] = new \Mautic\PageBundle\Helper\TrackingHelper(($this->services['session'] ?? $this->getSessionService()), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['mautic.tracker.contact'] ?? $this->getMautic_Tracker_ContactService()));
