<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.sync.data_exchange.mautic.order_executioner' shared service.

return $this->services['mautic.integrations.sync.data_exchange.mautic.order_executioner'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\Executioner\OrderExecutioner(($this->services['mautic.integrations.helper.sync_mapping'] ?? $this->load('getMautic_Integrations_Helper_SyncMappingService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['mautic.integrations.internal.object_provider'] ?? $this->load('getMautic_Integrations_Internal_ObjectProviderService.php')));
