<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.channel.campaignbundle.subscriber' shared service.

return $this->services['mautic.channel.campaignbundle.subscriber'] = new \Mautic\ChannelBundle\EventListener\CampaignSubscriber(($this->services['mautic.channel.model.message'] ?? $this->load('getMautic_Channel_Model_MessageService.php')), ($this->services['mautic.campaign.dispatcher.action'] ?? $this->load('getMautic_Campaign_Dispatcher_ActionService.php')), ($this->services['mautic.campaign.event_collector'] ?? $this->load('getMautic_Campaign_EventCollectorService.php')), ($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
