<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.fixture.test.tag' shared service.

return $this->services['mautic.lead.fixture.test.tag'] = new \Mautic\LeadBundle\Tests\DataFixtures\ORM\LoadTagData();
