<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.fixture.segment' shared service.

return $this->services['mautic.lead.fixture.segment'] = new \Mautic\LeadBundle\DataFixtures\ORM\LoadLeadListData(($this->services['mautic.lead.model.list'] ?? $this->getMautic_Lead_Model_ListService()));
