<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.api.oauth2.authorize_controller' shared service.

return $this->services['mautic.api.oauth2.authorize_controller'] = new \Mautic\ApiBundle\Controller\oAuth2\AuthorizeController(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->privates['fos_oauth_server.authorize.form'] ?? $this->load('getFosOauthServer_Authorize_FormService.php')), ($this->privates['fos_oauth_server.authorize.form.handler.default'] ?? $this->load('getFosOauthServer_Authorize_Form_Handler_DefaultService.php')), ($this->privates['fos_oauth_server.server'] ?? $this->load('getFosOauthServer_ServerService.php')), ($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->services['router'] ?? $this->getRouterService()), ($this->privates['fos_oauth_server.client_manager.default'] ?? $this->load('getFosOauthServer_ClientManager_DefaultService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['session'] ?? $this->getSessionService()));
