<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.user_list' shared service.

return $this->services['mautic.form.type.user_list'] = new \Mautic\UserBundle\Form\Type\UserListType(($this->services['mautic.user.model.user'] ?? $this->getMautic_User_Model_UserService()));
