<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.plugin.clearbit.lead.subscriber' shared service.

return $this->services['mautic.plugin.clearbit.lead.subscriber'] = new \MauticPlugin\MauticClearbitBundle\EventListener\LeadSubscriber(($this->services['mautic.plugin.clearbit.lookup_helper'] ?? $this->load('getMautic_Plugin_Clearbit_LookupHelperService.php')));
