<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.campaignbundle.action_dnc.subscriber' shared service.

return $this->services['mautic.lead.campaignbundle.action_dnc.subscriber'] = new \Mautic\LeadBundle\EventListener\CampaignActionDNCSubscriber(($this->services['mautic.lead.model.dnc'] ?? $this->load('getMautic_Lead_Model_DncService.php')), ($this->services['mautic.lead.model.lead'] ?? $this->getMautic_Lead_Model_LeadService()));
