<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.notification.campaignbundle.condition_subscriber' shared service.

return $this->services['mautic.notification.campaignbundle.condition_subscriber'] = new \Mautic\NotificationBundle\EventListener\CampaignConditionSubscriber();
