<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.helper.assetgeneration' shared service.

return $this->services['mautic.helper.assetgeneration'] = new \Mautic\CoreBundle\Helper\AssetGenerationHelper(($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))), ($this->services['mautic.helper.bundle'] ?? $this->getMautic_Helper_BundleService()), ($this->services['mautic.helper.paths'] ?? $this->getMautic_Helper_PathsService()), ($this->services['mautic.helper.app_version'] ?? ($this->services['mautic.helper.app_version'] = new \Mautic\CoreBundle\Helper\AppVersion())));
