<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.email.model.transport_callback' shared service.

return $this->services['mautic.email.model.transport_callback'] = new \Mautic\EmailBundle\Model\TransportCallback(($this->services['mautic.lead.model.dnc'] ?? $this->load('getMautic_Lead_Model_DncService.php')), ($this->services['mautic.message.search.contact'] ?? $this->load('getMautic_Message_Search_ContactService.php')), ($this->services['mautic.email.repository.stat'] ?? $this->load('getMautic_Email_Repository_StatService.php')));
