<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.plugin.formbundle.subscriber' shared service.

$this->services['mautic.plugin.formbundle.subscriber'] = $instance = new \Mautic\PluginBundle\EventListener\FormSubscriber();

$instance->setIntegrationHelper(($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()));

return $instance;
