<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic_integration.pipedrive.data_push' shared service.

return $this->services['mautic_integration.pipedrive.data_push'] = new \MauticPlugin\MauticCrmBundle\Command\PushDataToPipedriveCommand(($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()), ($this->services['templating.helper.translator'] ?? $this->load('getTemplating_Helper_TranslatorService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['mautic_integration.pipedrive.export.company'] ?? $this->load('getMauticIntegration_Pipedrive_Export_CompanyService.php')), ($this->services['mautic_integration.pipedrive.export.lead'] ?? $this->load('getMauticIntegration_Pipedrive_Export_LeadService.php')));
