<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.integrations.form.config.sync_settings_object_field_directions' shared service.

return $this->services['mautic.integrations.form.config.sync_settings_object_field_directions'] = new \Mautic\IntegrationsBundle\Form\Type\IntegrationSyncSettingsObjectFieldType();
