<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.plugin.integration.subscriber' shared service.

return $this->services['mautic.plugin.integration.subscriber'] = new \Mautic\PluginBundle\EventListener\IntegrationSubscriber(($this->services['monolog.logger.mautic'] ?? $this->getMonolog_Logger_MauticService()));
