<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.transport.sendgrid_api.mail.base' shared service.

return $this->services['mautic.transport.sendgrid_api.mail.base'] = new \Mautic\EmailBundle\Swiftmailer\SendGrid\Mail\SendGridMailBase(($this->services['mautic.helper.plain_text_message'] ?? ($this->services['mautic.helper.plain_text_message'] = new \Mautic\EmailBundle\Helper\PlainTextMessageHelper())));
