<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.form.type.field_propertyemail' shared service.

return $this->services['mautic.form.type.field_propertyemail'] = new \Mautic\FormBundle\Form\Type\FormFieldEmailType(($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
