<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.lead.subscriber.filterOperator' shared service.

return $this->services['mautic.lead.subscriber.filterOperator'] = new \Mautic\LeadBundle\EventListener\FilterOperatorSubscriber(($this->services['mautic.lead.segment.operator_options'] ?? ($this->services['mautic.lead.segment.operator_options'] = new \Mautic\LeadBundle\Segment\OperatorOptions())), ($this->services['mautic.lead.repository.field'] ?? $this->getMautic_Lead_Repository_FieldService()), ($this->services['mautic.lead.provider.typeOperator'] ?? $this->load('getMautic_Lead_Provider_TypeOperatorService.php')), ($this->services['mautic.lead.provider.fieldChoices'] ?? $this->load('getMautic_Lead_Provider_FieldChoicesService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
