<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.stage.type.form' shared service.

return $this->services['mautic.stage.type.form'] = new \Mautic\StageBundle\Form\Type\StageType(($this->services['mautic.security'] ?? $this->getMautic_SecurityService()));
