<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.update.step.delete_cache' shared service.

return $this->services['mautic.update.step.delete_cache'] = new \Mautic\CoreBundle\Update\Step\DeleteCacheStep(($this->services['mautic.helper.cache'] ?? $this->load('getMautic_Helper_CacheService.php')), ($this->services['translator.default'] ?? $this->getTranslator_DefaultService()));
