<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.command.clear_chunks' shared service.

$this->privates['oneup_uploader.command.clear_chunks'] = $instance = new \Oneup\UploaderBundle\Command\ClearChunkCommand(($this->services['oneup_uploader.chunk_manager'] ?? $this->load('getOneupUploader_ChunkManagerService.php')));

$instance->setName('oneup:uploader:clear-chunks');

return $instance;
