<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mautic\PluginBundle\Command\PushLeadActivityCommand' shared autowired service.

return $this->services['Mautic\\PluginBundle\\Command\\PushLeadActivityCommand'] = new \Mautic\PluginBundle\Command\PushLeadActivityCommand();
