<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating.twig.extension.gravatar' shared service.

return $this->services['templating.twig.extension.gravatar'] = new \Mautic\CoreBundle\Templating\Twig\Extension\GravatarExtension(($this->services['mautic.helper.template.gravatar'] ?? $this->load('getMautic_Helper_Template_GravatarService.php')));
