<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating.twig.extension.menu' shared service.

return $this->services['templating.twig.extension.menu'] = new \Mautic\CoreBundle\Templating\Twig\Extension\MenuExtension(($this->services['mautic.helper.template.menu'] ?? $this->load('getMautic_Helper_Template_MenuService.php')));
