<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'transifex.factory' shared service.

return $this->services['transifex.factory'] = new \Mautic\CoreBundle\Factory\TransifexFactory(($this->services['mautic.http.client'] ?? ($this->services['mautic.http.client'] = new \GuzzleHttp\Client())), ($this->services['mautic.helper.core_parameters'] ?? ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))));
