<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating.twig.extension.form' shared service.

return $this->services['templating.twig.extension.form'] = new \Mautic\CoreBundle\Templating\Twig\Extension\FormExtension();
