<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mautic\LeadBundle\Command\UpdateLeadListsCommand' shared autowired service.

return $this->services['Mautic\\LeadBundle\\Command\\UpdateLeadListsCommand'] = new \Mautic\LeadBundle\Command\UpdateLeadListsCommand();
