<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => 'ma_',
	'db_port' => '3306',
	'db_name' => 'tianwing_test1',
	'db_user' => 'tianwing_tianwin',
	'db_password' => 'Dong2000jiao',
	'db_backup_tables' => null,
	'db_backup_prefix' => 'bak_',
	'mailer_from_name' => 'Site Owner',
	'mailer_from_email' => 'devnull@installatron.com',
	'mailer_transport' => 'sendmail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_amazon_region' => null,
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/var/spool',
	'secret_key' => 'c0fdabd9fa87dae60d6c448c4c0c96d651df8641f19b3284d2c6ac4647936dd6',
	'site_url' => 'http://tianwin.georgetown.domains/stats1',
);
